//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocImageClient.DocImageReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DocImageReference.IDocImageServer")]
    public interface IDocImageServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocImageServer/GetData", ReplyAction="http://tempuri.org/IDocImageServer/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocImageServer/GetData", ReplyAction="http://tempuri.org/IDocImageServer/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocImageServer/scrapeTest", ReplyAction="http://tempuri.org/IDocImageServer/scrapeTestResponse")]
        string scrapeTest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocImageServer/scrapeTest", ReplyAction="http://tempuri.org/IDocImageServer/scrapeTestResponse")]
        System.Threading.Tasks.Task<string> scrapeTestAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDocImageServerChannel : DocImageClient.DocImageReference.IDocImageServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocImageServerClient : System.ServiceModel.ClientBase<DocImageClient.DocImageReference.IDocImageServer>, DocImageClient.DocImageReference.IDocImageServer {
        
        public DocImageServerClient() {
        }
        
        public DocImageServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocImageServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocImageServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocImageServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public string scrapeTest() {
            return base.Channel.scrapeTest();
        }
        
        public System.Threading.Tasks.Task<string> scrapeTestAsync() {
            return base.Channel.scrapeTestAsync();
        }
    }
}
