//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocImageClient.DocImageServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DocImageServiceReference.IDocImageServer")]
    public interface IDocImageServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocImageServer/GetData", ReplyAction="http://tempuri.org/IDocImageServer/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocImageServer/GetData", ReplyAction="http://tempuri.org/IDocImageServer/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocImageServer/scrapeTest", ReplyAction="http://tempuri.org/IDocImageServer/scrapeTestResponse")]
        System.Collections.Generic.Dictionary<string, bool> scrapeTest(string hstNumber, string legalName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocImageServer/scrapeTest", ReplyAction="http://tempuri.org/IDocImageServer/scrapeTestResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, bool>> scrapeTestAsync(string hstNumber, string legalName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDocImageServerChannel : DocImageClient.DocImageServiceReference.IDocImageServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocImageServerClient : System.ServiceModel.ClientBase<DocImageClient.DocImageServiceReference.IDocImageServer>, DocImageClient.DocImageServiceReference.IDocImageServer {
        
        public DocImageServerClient() {
        }
        
        public DocImageServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocImageServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocImageServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocImageServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public System.Collections.Generic.Dictionary<string, bool> scrapeTest(string hstNumber, string legalName) {
            return base.Channel.scrapeTest(hstNumber, legalName);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, bool>> scrapeTestAsync(string hstNumber, string legalName) {
            return base.Channel.scrapeTestAsync(hstNumber, legalName);
        }
    }
}
